server:
  port: 18080

spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhbreeze/msa-config-server.git
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/