spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5433/msa_user
    username: admin1
    password: admin2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  register-with-eureka: true
  fetch-registry: true

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: refresh
