message: application dev profile

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5433/msa_user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  register-with-eureka: true
  fetch-registry: true

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh
